# Generated by Django 4.2.22 on 2025-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('issue_status_change', 'Issue Status Change'), ('issue_comment', 'Issue Comment'), ('issue_assigned', 'Issue Assigned'), ('issue_resolved', 'Issue Resolved'), ('system_message', 'System Message'), ('welcome', 'Welcome Message')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_issue_updates', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_assignments', models.BooleanField(default=True)),
                ('email_system_messages', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('push_issue_updates', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_assignments', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('issue_status_change', 'Issue Status Change'), ('issue_comment', 'Issue Comment'), ('issue_assigned', 'Issue Assigned'), ('issue_resolved', 'Issue Resolved'), ('system_message', 'System Message'), ('welcome', 'Welcome Message')], max_length=50)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
    ]
