# Generated by Django 4.2.22 on 2025-08-02 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueupdate',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuephoto',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueflag',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_instances', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueassignment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.category'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='issuevote',
            unique_together={('issue', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='issueflag',
            unique_together={('issue', 'user')},
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'priority'], name='issues_status_88878d_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category', 'status'], name='issues_categor_81e5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['reported_at'], name='issues_reporte_c0efcd_idx'),
        ),
    ]
