# Generated by Django 4.2.7 on 2026-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_ai_confidence_issue_ai_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
