# Generated by Django 4.2.7 on 2026-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ai_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='ai_severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
    ]
