# Generated by Django 4.2.7 on 2026-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_ai_priority_alter_issue_ai_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
